package com.richway.basic.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

@Service
public class RoleServiceImpl implements RoleService {

	@Autowired
	private JdbcTemplate jdbcTemplate;
	
	@Override
	public void createRoleTable() {
		jdbcTemplate.update("CREATE TABLE PUBLIC.ROLE(ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,ROLENAME VARCHAR(20),SORTID INTEGER)");
	}

}
