package com.richway.basic.service;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;

import org.springframework.beans.BeanWrapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.PreparedStatementSetter;
import org.springframework.stereotype.Service;

import com.richway.basic.domain.User;

@Service
public class UserServiceImpl implements UserService {

	@Autowired
	private JdbcTemplate jdbcTemplate;
	
	@Override
	public void create(String name, Integer age) {
		jdbcTemplate.update("insert into USER(NAME, AGE) values(?, ?)", name, age);
	}

	@Override
	public void deleteByName(String name) {
		//parame
		PreparedStatementSetter setter=new PreparedStatementSetter() {
			@Override
			public void setValues(PreparedStatement ps) throws SQLException {
				ps.setString(1, name);
			}
		};
		
		jdbcTemplate.update("delete from USER where name=?",setter);

	}

	@Override
	public Integer getAllUsers() {
		return jdbcTemplate.queryForObject("select count(name) from USER", Integer.class);
	}
	
	@Override
	public List<User> getAllUsersList() {
		//return jdbcTemplate.queryForList("select id,name,age from USER",User.class);
		return jdbcTemplate.query("select id,name,age from USER", rowMapper);
	}
	
	private BeanPropertyRowMapper<User> rowMapper = new BeanPropertyRowMapper<User>(User.class){    
        @Override    
        protected void initBeanWrapper(BeanWrapper bw) {    
            super.initBeanWrapper(bw);    
        }    
    };   

	@Override
	public void deleteAllUsers() {
		// TODO Auto-generated method stub

	}

	@Override
	public void createUserTable() {
		jdbcTemplate.update("CREATE TABLE PUBLIC.USER(ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,NAME VARCHAR(20),AGE INTEGER)");
	}

}
